/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app-footer.vue')['default']
    AppHeader: typeof import('./components/app-header.vue')['default']
    CodeMirror: typeof import('./components/codemirror/CodeMirror.vue')['default']
    JsxEditor: typeof import('./components/jsx-editor.vue')['default']
  }
}
